export const events = [
    {
        title: "Next.js Conf 2025",
        image: "/images/event1.png",
        slug: "nextjs-conf-2025",
        location: "San Francisco, CA",
        date: "October 25, 2025",
        time: "10:00 AM",
    },
    {
        title: "React Summit",
        image: "/images/event2.png",
        slug: "react-summit",
        location: "Amsterdam, NL",
        date: "June 14, 2025",
        time: "09:00 AM",
    },
    {
        title: "JSWorld Conference",
        image: "/images/event3.png",
        slug: "jsworld-conference",
        location: "Paris, FR",
        date: "February 12, 2025",
        time: "08:30 AM",
    },
    {
        title: "Web Summit 2025",
        image: "/images/event4.png",
        slug: "web-summit-2025",
        location: "Lisbon, PT",
        date: "November 11, 2025",
        time: "11:00 AM",
    },
    {
        title: "Node Congress",
        image: "/images/event5.png",
        slug: "node-congress",
        location: "Berlin, DE",
        date: "April 18, 2025",
        time: "09:30 AM",
    },
    {
        title: "AI Engineer Summit",
        image: "/images/event6.png",
        slug: "ai-engineer-summit",
        location: "New York, NY",
        date: "September 05, 2025",
        time: "10:00 AM",
    },
];
